micronaut:
  application:
    name: micronaut
  server:
    port: 8081
---
datasources:
  default:
    url: jdbc:mysql://localhost:3306/products
    username: root
    password: 35Kvg42OpY
    dialect: MYSQL
---
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
